@startuml
left to right direction
actor "HR-менеджер" as HR
actor "Администратор подразделения" as Admin

rectangle "Управление подразделениями" {
  usecase "Создать подразделение" as UC1
  usecase "Проверить уникальность названия" as UC2
  usecase "Определить иерархию" as UC3
  usecase "Выбрать локации" as UC4
  usecase "Добавить новую локацию" as UC5
  usecase "Обновить сведения о подразделении" as UC6
}

HR --> UC1
Admin --> UC6
UC1 ..> UC2 : <<include>>
UC1 ..> UC3 : <<include>>
UC1 ..> UC4 : <<include>>
UC4 <.. UC5 : <<extend>>
@enduml